// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iozyxewnupuzckwxwpqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvenl4ZXdudXB1emNrd3h3cHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODI2NTksImV4cCI6MjA3Mjc1ODY1OX0.E3IAzsXl287SCvJxr3av1kNzEuiQwTwQU9FjIpdrqrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});